# Generated by Django 6.0 on 2025-12-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('course', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
